package platform

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

type linuxAdapter struct{}

func newLinuxAdapter() *linuxAdapter {
	return &linuxAdapter{}
}

func (l *linuxAdapter) PlatformName() string {
	return "linux"
}

func (l *linuxAdapter) RequiresElevation() bool {
	return false
}

func (l *linuxAdapter) SetProxy(config ProxyConfig) error {
	home, _ := os.UserHomeDir()
	envFile := home + "/.netenv_proxy_env"

	var lines []string
	if config.HTTP != "" {
		lines = append(lines, fmt.Sprintf("export HTTP_PROXY=%q", config.HTTP))
		lines = append(lines, fmt.Sprintf("http_proxy=%q", config.HTTP))
	}
	if config.HTTPS != "" {
		lines = append(lines, fmt.Sprintf("export HTTPS_PROXY=%q", config.HTTPS))
		lines = append(lines, fmt.Sprintf("https_proxy=%q", config.HTTPS))
	}
	if config.SOCKS5 != "" {
		lines = append(lines, fmt.Sprintf("export ALL_PROXY=%q", config.SOCKS5))
	}
	if len(config.NoProxy) > 0 {
		noProxy := strings.Join(config.NoProxy, ",")
		lines = append(lines, fmt.Sprintf("export NO_PROXY=%q", noProxy))
	}

	data := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(envFile, []byte(data), 0644); err != nil {
		return fmt.Errorf("failed to write proxy env file: %w", err)
	}

	for _, line := range lines {
		line = strings.TrimPrefix(line, "export ")
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			os.Setenv(parts[0], strings.Trim(parts[1], "\""))
		}
	}

	return nil
}

func (l *linuxAdapter) ClearProxy() error {
	home, _ := os.UserHomeDir()
	envFile := home + "/.netenv_proxy_env"
	os.Remove(envFile)

	for _, key := range []string{"HTTP_PROXY", "http_proxy", "HTTPS_PROXY", "https_proxy", "ALL_PROXY", "NO_PROXY"} {
		os.Unsetenv(key)
	}

	return nil
}

func (l *linuxAdapter) SetDNS(config DNSConfig) error {
	var content strings.Builder
	content.WriteString("# Generated by netenv\n")

	for _, server := range config.Servers {
		content.WriteString(fmt.Sprintf("nameserver %s\n", server))
	}

	if len(config.SearchDomains) > 0 {
		content.WriteString(fmt.Sprintf("search %s\n", strings.Join(config.SearchDomains, " ")))
	}

	if err := os.WriteFile("/etc/resolv.conf", []byte(content.String()), 0644); err != nil {
		cmd := exec.Command("sudo", "tee", "/etc/resolv.conf")
		cmd.Stdin = strings.NewReader(content.String())
		if output, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("failed to write resolv.conf: %w (%s)", err, string(output))
		}
	}

	return nil
}

func (l *linuxAdapter) ClearDNS() error {
	cmd := exec.Command("sudo", "bash", "-c", "echo '# /etc/resolv.conf' > /etc/resolv.conf")
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to clear DNS: %w (%s)", err, string(output))
	}
	return nil
}

func (l *linuxAdapter) SetEnvVars(vars map[string]string) error {
	home, _ := os.UserHomeDir()
	profilePath := home + "/.bashrc"

	f, err := os.OpenFile(profilePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("failed to open shell profile: %w", err)
	}
	defer f.Close()

	for key, value := range vars {
		line := fmt.Sprintf("export %s=\"%s\"\n", key, value)
		if _, err := f.WriteString(line); err != nil {
			return fmt.Errorf("failed to write env var %s: %w", key, err)
		}
		os.Setenv(key, value)
	}

	return nil
}

func (l *linuxAdapter) GetEnvVars(keys []string) (map[string]string, error) {
	result := make(map[string]string)
	for _, key := range keys {
		result[key] = os.Getenv(key)
	}
	return result, nil
}

func (l *linuxAdapter) FlushDNS() error {
	for _, cmdStr := range []string{
		"resolvectl flush-caches",
		"systemd-resolve --flush-caches",
	} {
		cmd := exec.Command("sudo", "bash", "-c", cmdStr)
		if err := cmd.Run(); err == nil {
			return nil
		}
	}
	return nil
}
